# These rules apply to the Nitro Umbrella app and all components.
# Rule modifications should go here to maintain consistency between components and the umbrella application.

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/schema.rb'
    - '**/bin/*'
    - 'vendor/**/*'
    - '**/*.rake'

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them when introducing an interpolation.
# Use single quotes only if their semantics are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/db/migrate/*'
