module Names
  FOR_2016 = [
    "Tim McKay",
    "Marianne McKay",
    "Ryan McKay",
    "Adam McKay",
    "JD Grace",
    "Barb Grace",
    "Jeff Mortensen",
    "Rachel Mortensen",
    "Donn Polzin",
    "Luke Berg",
    "Cassie McKay",
    "Evelyn McKay",
    "Dustin Polzin",
    "Garett Arrowood",
    "Josh Chojnaski",
    "Dave Faber",
    "Steven Hessler",
    "Sorana Popa",
    "Greg Davis",
    "Adam Gander",
    "David Trautschold",
    "Austin Konz",
    "David Kron",
    "Mandy Kron",
    "Kathy Short",
    "Teddy Short",
    "Kyle Oksiuta",
    "King Tut"
  ]

  FOR_2017 = [
    "Tim McKay",
    "Marianne McKay",
    "Adam McKay",
    "Derrick Sherer",
    "JD Grace",
    "Barb Grace",
    "Jeff Mortensen",
    "Rachel Mortensen",
    "Donn Polzin",
    "Matt Polzin",
    "Alison Hangen",
    "Dustin Polzin",
    "Luke Berg",
    "Garett Arrowood",
    "Josh Chojnaski",
    "Greg Davis",
    "Steven Hessler",
    "Sorana Hessler"
  ]
end
